---
title: "Lecture7"
author: "Me"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
```

# modeling
```{r}
p<-ggplot(sim1,aes(x,y))+geom_point()
p
```

```{r}
models<-tibble(
  a1=runif(250,-20,40),
  a2=runif(250,-5,5)
)
p+geom_abline(aes(intercept=a1,slope=a2),data=models,alpha=0.25)  # just some random lines
```
```{r}
model1<-function(a,data){  # the calculated y
  a[1]+data$x*a[2]
}
#model1(c(7.5,1.5),sim1)
measure_distance<-function(mod,data){    # difference between claculated y and real y
  diff<-data$y-model1(mod,data)
  sqrt(mean(diff^2))   # square mean error
}

measure_distance(c(7.5,1.5),sim1)
```
```{r}
sim1_dist<-function(a1,a2){
  measure_distance(c(a1,a2),sim1)
}
models<-models%>%
  mutate(dist=purrr::map2_dbl(a1,a2,sim1_dist))
models   # contains all kinds of combinations of a1 and a2, and you want the dist to be as low as possible
```

```{r}
p+geom_abline(
  aes(intercept=a1,slope=a2,color=-dist),
  data=filter(models,rank(dist)<=10)   # figure out the 10 lines with the lowest dist
)
```
```{r}
ggplot(models,aes(a1,a2))+
  geom_point(data=filter(models,rank(dist)<=10),size=4,color="red")+
  geom_point(aes(color=-dist))
# pick out the combination of the interceptions and slops with the lowest dist
```
```{r}
grid<-expand.grid(  # grid search !!!
  a1=seq(-5,20,length=25),
  a2=seq(1,3,length=25)
)%>%
  mutate(dist=purrr::map2_dbl(a1,a2,sim1_dist))

grid%>%
  ggplot(aes(a1,a2))+
  geom_point(data=filter(grid,rank(dist)<=10),size=4,color="red")+
  geom_point(aes(color=-dist))

```
```{r}
p+geom_abline(
  aes(intercept=a1,slope=a2,color=-dist),
  data=filter(grid,rank(dist)<=10)
)

```

```{r}
best<-optim(c(0,0),measure_distance,data=sim1) # pick out the best one
best$par
p+geom_abline(intercept = best$par[1],slope = best$par[2])
```

```{r}
sim1_mod<-lm(y~x,data=sim1)  # now use the linear regression function directly
coef(sim1_mod)
```

# non linear squares
```{r}
as_tibble(Puromycin)
summary(Puromycin)

```
```{r}
p<-ggplot(Puromycin,aes(conc,rate,color=state))+
  geom_point()+
  coord_cartesian(ylim=c(0,210))+
  labs(
    x="Substrate concentration (ppm)",
    y="Reaction velocity (counts/min^2)"
  )
p
```
```{r}
treated<-Puromycin%>%
  filter(state=="treated")%>% as_tibble()

untreated<-Puromycin%>%
  filter(state=="untreated")%>% as_tibble()

treated_model<-nls(   # also use the built functions to generate non linear regression
  rate~Vm*conc/(Km+conc),
  data=treated,
  start=c(Vm=200,Km=0.05)
)

untreated_model<-nls(
  rate~Vm*conc/(Km+conc),
  data=untreated,
  start=c(Vm=100,Km=0.05)
)
View(untreated_model)
```

```{r}
summary(treated_model)
```
```{r}
confint(treated_model)   # confident intervals for the paremeters
confint(untreated_model)
```

```{r}
treated_curve<-tibble(   # draw the regression curves with a group of dots
  conc=seq(0,max(treated$conc),length.out=201),
)%>%
  modelr::add_predictions(treated_model)%>%
  rename(rate=pred)%>%
  mutate(state="treated")

untreated_curve<-tibble(
  conc=seq(0,max(untreated$conc),length.out=201),
)%>%
  modelr::add_predictions(untreated_model)%>%
  rename(rate=pred)%>%
  mutate(state="untreated")

curves<-rbind(treated_curve,untreated_curve)
```


```{r}
p+geom_line(data=curves)
```























