---
title: "Lecture6"
author: "Me"
date: "2/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Functions!
one concept one function
```{r name_here}
df<-tibble::tibble(
  a=rnorm(10),
  b=rnorm(10),
  c=rnorm(10),
  d=rnorm(10),
)
df
df$a<-(df$a-min(df$a,na.rm=TRUE))/(max(df$a,na.rm=TRUE)-min(df$a,na.rm=TRUE))
df
```

```{r name_here}
df<-tibble::tibble(
  a=rnorm(10),
  b=rnorm(10),
  c=rnorm(10),
  d=rnorm(10),
)
x<-df$a
xmin<-min(x,na.rm=TRUE)
xmax<-max(x,na.rm=TRUE)
df$a<-(x-xmin)/(xmax-xmin)
df
```

```{r name_here}
df<-tibble::tibble(
  a=rnorm(10),
  b=rnorm(10),
  c=rnorm(10),
  d=rnorm(10),
)

rescale01<-function(x){
  xmin<-min(x,na.rm=TRUE)
  xmax<-max(x,na.rm=TRUE)
  (x-xmin)/(xmax-xmin)
}

df$a<-rescale01(df$a)
df
```

```{r name_here}
df<-tibble::tibble(
  a=rnorm(10),
  b=rnorm(10),
  c=rnorm(10),
  d=rnorm(10),
)

rescale0m1<-function(x,rm=TRUE,scale_factor=1){
  xmean<-mean(x,na.rm=rm)
  xmin<-min(x,na.rm=TRUE)
  xmax<-max(x,na.rm=TRUE)
  scale_factor*(x-xmean)/(xmax-xmin)
}

df$a<-rescale0m1(df$a,scale_factor = 20)
df
```

# flow control, iteration
control by if
```{r}
wt_mean<-function(x,w){
  if (length(x)!=length(w)){
    stop("Not same length",call. = TRUE)
  }
  sum(x*w)/sum(w)
}

wt_mean(1:6,1:3)
```

```{r}
foo<-function(x){
  if (length(x)!=1){
    stop("not length 1")
  }
  if (x==3||x==7){
    return(-7)
  }else{
    return(100)
  }
}
foo(2)
```

## for loop
```{r}
df<-tibble::tibble(
  a=rnorm(11),
  b=rnorm(11),
  c=rnorm(11),
  d=rnorm(11),
)
df
output<-vector("double",ncol(df)) # generate a vwector which is the same length as the df
for (i in seq_along(df)){   # don't forget ()  # select by the indexes of columns
  output[[i]]<-median(df[[i]])
}
output
```

```{r}
xs<-c("a","b","c")
for (x in xs){
  print(x)
}
```
```{r}
for (nm in names(df)){   # select by the names of the columns
  print(nm)
  print(median(df[[nm]]))
}
```









